export const THEME = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
];

export const photoStyle = {
  light: "mask mask-squircle",
  dark: "mask mask-squircle",
  cupcake: "rounded-full",
  bumblebee: "mask mask-squircle",
  emerald: "mask mask-squircle",
  corporate: "mask mask-square",
  synthwave: "mask mask-squircle",
  retro: "mask mask-squircle",
  cyberpunk: "mask mask-square",
  valentine: "rounded-full",
  halloween: "mask mask-squircle",
  garden: "mask mask-squircle",
  forest: "rounded-full",
  aqua: "mask mask-squircle",
  lofi: "mask mask-square",
  pastel: "rounded-full",
  fantasy: "mask mask-squircle",
  wireframe: "mask mask-squircle",
  black: "mask mask-square",
  luxury: "mask mask-squircle",
  dracula: "mask mask-squircle",
  cmyk: "mask mask-squircle",
  autumn: "mask mask-squircle",
  business: "mask mask-square",
  acid: "mask mask-squircle",
  lemonade: "mask mask-squircle",
  night: "mask mask-squircle",
  coffee: "mask mask-squircle",
  winter: "mask mask-squircle",
};

export const colorHexTheme = {
  light: "570df8",
  dark: "661AE6",
  cupcake: "65c3c8",
  bumblebee: "e0a82e",
  emerald: "66cc8a",
  corporate: "4b6bfb",
  synthwave: "e779c1",
  retro: "ef9995",
  cyberpunk: "ff7598",
  valentine: "e96d7b",
  halloween: "f28c18",
  garden: "5c7f67",
  forest: "1eb854",
  aqua: "09ecf3",
  lofi: "0D0D0D",
  pastel: "d1c1d7",
  fantasy: "6e0b75",
  wireframe: "b8b8b8",
  black: "343232",
  luxury: "513448",
  dracula: "ff79c6",
  cmyk: "45AEEE",
  autumn: "8C0327",
  business: "1C4E80",
  acid: "FF00F4",
  lemonade: "519903",
  night: "38bdf8",
  coffee: "DB924B",
  winter: "047AFF",
};
